### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by edgrosvenor** [grosv/laravel-boilerplate#9]
# Day One Checklist
- [ ] Set up StyleCI
- [ ] Set Up ChipperCI
- [ ] Set Up Vapor Environments
- [ ] Set Up DNS

# Pre-Launch Checklist
- [ ] Move any temporary pre-launch functions that remain useful to secure, permanent locations
- [ ] Remove temporary routes from routes/web.php
- [ ] Remove App\Http\Controllers\Temporary and any associated templates
- [ ] Set APP_LAUNCHED to true in .env
